<?php

namespace Jm\ABBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
	public function findTemplateByName($name, $cacheTime)
	{
		try {
			$query = $this->createQueryBuilder('t')
				->where('t.name = :name')
				->setParameter('name', $name)
				->getQuery()
				->useResultCache(true, $cacheTime)
            ;

            $template = $query->getSingleResult();
        } catch (NoResultException $e) {
            $template = null;
        }

        return $template;
    }
}
